<?php

namespace App\Imports;

use App\Models\KwsKmhKrw;
use App\Models\Summary;
use Error;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithStartRow;
use Maatwebsite\Excel\Concerns\WithCalculatedFormulas;
use Illuminate\Support\Facades\DB;
use DateTime;

class KwsKmhKrwImport implements ToCollection, WithStartRow, WithCalculatedFormulas
{
    public function collection(Collection $cols)
    {
        foreach ($cols as $col) {
            try {
                $data = [
                    'provinsi' =>	$col[0],
                    'kota' =>	$col[1],
                    'kecamatan' =>	$col[2],
                    'kelurahan' =>	$col[3],
                    'bkm' =>	$col[4],
                    'bkm_status_berdaya' =>	$col[5],
                    'luas_kelurahan' =>	$col[6],
                    'tipologi_kelurahan' =>	$col[7],
                    'latitude_kelurahan' =>	$col[8],
                    'longitude_kelurahan' =>	$col[9],
                    'kategori_kota' =>	$col[10],
                    'nama_kawasan' =>	$col[11],
                    'rt' =>	$col[12],
                    'rw' =>	$col[13],
                    'luas_kawasan' =>	$col[14],
                    'jumlah_penduduk_kawasan' =>	$col[15],
                    'tahun' =>	$col[16],
                    'baseline_tahun' =>	$col[17],
                    'rt_rw_dusun' =>	$col[18],
                    'jumlah_krt' =>	$col[19],
                    'jumlah_kk' =>	$col[20],
                    'jumlah_krt_mbr' =>	$col[21],
                    'jumlah_krt_non_mbr' =>	$col[22],
                    'jumlah_penduduk_laki' =>	$col[23],
                    'jumlah_penduduk_perempuan' =>	$col[24],
                    'bk1' =>	$col[25],
                    'bk2' =>	$col[26],
                    'bk3' =>	$col[27],
                    'bk4' =>	$col[28],
                    'bk5' =>	$col[29],
                    'bk6' =>	$col[30],
                    'bk7' =>	$col[31],
                    'bk8' =>	$col[32],
                    'bk9' =>	$col[33],
                    'jk1' =>	$col[34],
                    'jk2' =>	$col[35],
                    'jk3' =>	$col[36],
                    'jk4' =>	$col[37],
                    'jk5' =>	$col[38],
                    'jk6' =>	$col[39],
                    'jk7' =>	$col[40],
                    'jk8' =>	$col[41],
                    'jk9' =>	$col[42],
                    'jk10' =>	$col[43],
                    'jk11' =>	$col[44],
                    'jk12' =>	$col[45],
                    'jk13' =>	$col[46],
                    'jk14' =>	$col[47],
                    'jk15' =>	$col[48],
                    'dk1' =>	$col[49],
                    'dk2' =>	$col[50],
                    'dk3' =>	$col[51],
                    'dk4' =>	$col[52],
                    'dk5' =>	$col[53],
                    'dk6' =>	$col[54],
                    'dk7' =>	$col[55],
                    'dk8' =>	$col[56],
                    'dk9' =>	$col[57],
                    'dk10' =>	$col[58],
                    'dk11' =>	$col[59],
                    'dk12' =>	$col[60],
                    'ak1' =>	$col[61],
                    'ak2' =>	$col[62],
                    'ak3' =>	$col[63],
                    'ak4' =>	$col[64],
                    'ak5' =>	$col[65],
                    'ak6' =>	$col[66],
                    'ak7' =>	$col[67],
                    'ak8' =>	$col[68],
                    'ak9' =>	$col[69],
                    'sk1' =>	$col[70],
                    'sk2' =>	$col[71],
                    'sk3' =>	$col[72],
                    'sk4' =>	$col[73],
                    'sk5' =>	$col[74],
                    'sk6' =>	$col[75],
                    'fk1' =>	$col[76],
                    'fk_27' =>	$col[77],
                    'fk2' =>	$col[78],
                    'fk3' =>	$col[79],
                    'fk4' =>	$col[80],
                    'fk5' =>	$col[81],
                    'lk1' =>	$col[82],
                    'lk2' =>	$col[83],
                    'lk3' =>	$col[84],
                    'lk4' =>	$col[85],
                    'pk24' =>	$col[86],
                    'pk25' =>	$col[87],
                    'pk26' =>	$col[88],
                    'mk1' =>	$col[89],
                    'mk2' =>	$col[90],
                    'mk3' =>	$col[91],
                    'mk4' =>	$col[92],
                    'mk5' =>	$col[93],
                    'mk6' =>	$col[94],
                    'mk7' =>	$col[95],
                    'ek1' =>	$col[96],
                    'ek2' =>	$col[97],
                    'ek3' =>	$col[98],
                    'ek4' =>	$col[99],
                    'ek5' =>	$col[100],
                    'kk1' =>	$col[101],
                    'kk2' =>	$col[102],
                    'kk3' =>	$col[103],
                    'kk4' =>	$col[104],
                    'kk5' =>	$col[105],
                    'kk6' =>	$col[106],
                    'kk7' =>	$col[107],
                    'kk8' =>	$col[108],
                    'kk9' =>	$col[109],
                    'kk10' =>	$col[110],
                    'kk11' =>	$col[111],
                    'bk10' =>	$col[112],
                    'bk11' =>	$col[113],
                    'bk12' =>	$col[114],
                    'jk16' =>	$col[115],
                    'jk17' =>	$col[116],
                    'jk18' =>	$col[117],
                    'ak10' =>	$col[118],
                    'ak11' =>	$col[119],
                    'dk13' =>	$col[120],
                    'dk14' =>	$col[121],
                    'dk15' =>	$col[122],
                    'dk16' =>	$col[123],
                    'dk17' =>	$col[124],
                    'dk18' =>	$col[125],
                    'ak12' =>	$col[126],
                    'ak13' =>	$col[127],
                    'sk7' =>	$col[128],
                    'sk8' =>	$col[129],
                    'sk9' =>	$col[130],
                    'fk6' =>	$col[131],
                    'fk7' =>	$col[132],
                    'bk13' =>	$col[133],
                    'bk14' =>	$col[134],
                    'bk15' =>	$col[135],
                    'bk16' =>	$col[136],
                    'bk17' =>	$col[137],
                    'bk18' =>	$col[138],
                    'jk19' =>	$col[139],
                    'jk20' =>	$col[140],
                    'jk21' =>	$col[141],
                    'jk22' =>	$col[142],
                    'ak14' =>	$col[143],
                    'ak15' =>	$col[144],
                    'ak16' =>	$col[145],
                    'ak17' =>	$col[146],
                    'dk19' =>	$col[147],
                    'dk20' =>	$col[148],
                    'dk21' =>	$col[149],
                    'dk22' =>	$col[150],
                    'dk23' =>	$col[151],
                    'dk24' =>	$col[152],
                    'dk25' =>	$col[153],
                    'dk26' =>	$col[154],
                    'dk27' =>	$col[155],
                    'dk28' =>	$col[156],
                    'ak18' =>	$col[157],
                    'ak19' =>	$col[158],
                    'ak20' =>	$col[159],
                    'ak21' =>	$col[160],
                    'sk10' =>	$col[161],
                    'sk11' =>	$col[162],
                    'sk12' =>	$col[163],
                    'sk13' =>	$col[164],
                    'sk14' =>	$col[165],
                    'sk15' =>	$col[166],
                    'fk8' =>	$col[167],
                    'fk9' =>	$col[168],
                    'fk10' =>	$col[169],
                    'fk11' =>	$col[170],
                    'skor_kekumuhan' =>	$col[171],
                    'tingkat_kekumuhan' =>	$col[172],
                    'bk19' => 0,
                ];
                // dd($data);
                // if($data['provinsi'] != 0) {
                    KwsKmhKrw::create($data);
                // }
            } catch (\Throwable $th) {
                // dd($th);
                continue;
            }
        }
    }

    public function startRow(): int
    {
        return 3;
    }
}
